### PR TITLE
Linear cell mode

### PR DESCRIPTION
**Pull request by choldgraf**
A few changes to add to the clearafter...does the following things:

When a cell is run:

* The N+1th cell gets a "stale" class added to it
* The > N+1th cell gets a "stale" class added and becomes uneditable
When a cell that is stale is run:

* All cells above this one which are also stale are run (in order) first

I also refactored the logic a little bit...

Stuff that is broken or needs doing:

* I can't figure out how to get the CSS to load
* The "all previous stale cells run first" bit is executed _after_ the current cell is run, but it should be before
* There should be a button somewhere to switch this on or off

An example of what this looks like:

(NOTE: this is just my general thinking+suggestions here, lemme know what you think)

### CODE REVIEW

**Comment by choldgraf** [comment]
OK I think the latest version works. See the attached GIF of what it looks like (I chose an example where we redefine "data" a few times and visualize it each time, then show how the confusion could be avoided w/ linear mode on.

(disregard the exact position of the cursor, it's my GIF recording thing being wonky)

**Comment by choldgraf** [comment]
(note that we may wanna change some UX things...I'm still not sold on making stale cells uneditable, but I do like making them greyed out etc)

**Comment by choldgraf** [comment]
@yuvipanda would you rather I close this PR? It sounds like there are other tools in this space as well (e.g., https://github.com/stitchfix/nodebook) so I'm not sure if you intend on continuing on this project. LMK!

**Comment by yuvipanda** [comment]
@choldgraf I made you a collaborator :) do what you think is right!

**Comment by choldgraf** [comment]
I think I'm gonna close this one, since neither of us seem to have the time to work on this repo, LMK if you disagree and happy to make a push if needed!

**Pull request closed without merging**
